require 'rake'
require 'rake/rdoctask'
require 'spec/rake/spectask'

Spec::Rake::SpecTask.new(:spec) do |task|
    task.spec_files = FileList['**/*_spec.rb']
end

Rake::RDocTask.new(:rdoc) do |task|
    task.rdoc_dir = 'doc'
    task.title    = 'DistribuStream'
    task.rdoc_files.include('bin/**/*.rb')
    task.rdoc_files.include('lib/**/*.rb')
    task.rdoc_files.include('simulation/**/*.rb')
end

file "lib/server/server_chunk_transfer.sm"
file "lib/client/client_chunk_transfer.sm"

file "lib/server/server_chunk_transfer_sm.rb" => ["lib/server/server_chunk_transfer.sm"] do |t|
  sh "java -jar lib/smc/bin/Smc.jar -ruby #{t.prerequisites[0]}"
end

file "lib/client/client_chunk_transfer_sm.rb" => ["lib/client/client_chunk_transfer.sm"] do |t|
  sh "java -jar lib/smc/bin/Smc.jar -ruby #{t.prerequisites[0]}"
end

task :smc => ["lib/client/client_chunk_transfer_sm.rb","lib/server/server_chunk_transfer_sm.rb"]

task :default => :smc
