require 'rake'
require 'rake/rdoctask'
require 'spec/rake/spectask'

Spec::Rake::SpecTask.new(:spec) do |task|
    task.spec_files = FileList['**/*_spec.rb']
end

Rake::RDocTask.new(:rdoc) do |task|
    task.rdoc_dir = 'doc'
    task.title    = 'DistribuStream'
    task.rdoc_files.include('bin/**/*.rb')
    task.rdoc_files.include('lib/**/*.rb')
    task.rdoc_files.include('simulation/**/*.rb')
end
